{% set name = "grpc-cpp" %}
{% set version = "1.36.4" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/grpc/grpc/archive/v{{ version }}.tar.gz
  sha256: 8eb9d86649c4d4a7df790226df28f081b97a62bf12c5c5fe9b5d31a29cd6541a
  patches:
    - aarch64-tcp-header.patch  # [aarch64]
    - force-protoc-executable.patch

build:
  number: 2
  string: h{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage('grpc-cpp', max_pin='x.x') }}
  ignore_run_exports:
    - abseil-cpp
    - openssl
    - re2
    - c-ares

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    # `protoc` is also used for building
    - libprotobuf {{ protobuf }}
    - ninja
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
    # We need all host deps also in build for cross-compiling
    - abseil-cpp  # [build_platform != target_platform]
    - c-ares      # [build_platform != target_platform]
    - re2         # [build_platform != target_platform]
    - openssl     # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - abseil-cpp  {{ abseil_cpp }}
    - c-ares
    - libprotobuf {{ protobuf }}
    - re2
    - openssl     # [not (x86_64 and c_compiler_version == "7.2.*")]
    - zlib
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
    - openssl 1.1.1k                  # [x86_64 and c_compiler_version == "7.2.*"]
  run:
    - zlib

test:
  files:
    - tests/include/*
  commands:
    - grpc_cpp_plugin < /dev/null

    - test -f $PREFIX/lib/libgrpc.so
    - test -f $PREFIX/lib/libgrpc_unsecure.so
    - test -f $PREFIX/lib/libgrpc++.so
    - test -f $PREFIX/lib/libgrpc++_unsecure.so

about:
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
  description: |
    gRPC is a modern, open source, high-performance remote procedure call
    (RPC) framework that can run anywhere. gRPC enables client and server
    applications to communicate transparently, and simplifies the building
    of connected systems.

    This package contains the gRPC C++ libraries and header files, as well
    as the code generation plugins.
  doc_url: https://grpc.io/docs/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
