{% set name = "grpc-cpp" %}
{% set version = "1.41.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/grpc/grpc/archive/v{{ version }}.tar.gz
  sha256: e5fb30aae1fa1cffa4ce00aa0bbfab908c0b899fcf0bbc30e268367d660d8656 
  patches:
    - aarch64-tcp-header.patch  # [aarch64]
    - force-protoc-executable.patch

build:
  number: 4
  string: h{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage('grpc-cpp', max_pin='x.x') }}
  ignore_run_exports:
    - abseil-cpp
    - openssl
    - re2
    - c-ares

requirements:
  build:
    - {{ compiler('c') }}             #[ppc_arch != "p10"]
    - {{ compiler('cxx') }}           #[ppc_arch != "p10"]
    - cmake
    # `protoc` is also used for building
    - libprotobuf {{ protobuf }}
    - ninja
    # We need all host deps also in build for cross-compiling
    - abseil-cpp  # [build_platform != target_platform]
    - c-ares      # [build_platform != target_platform]
    - re2         # [build_platform != target_platform]
    - openssl     # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - abseil-cpp  {{ abseil_cpp }}
    - c-ares
    - libprotobuf {{ protobuf }}
    - re2
    - zlib
    - openssl
  run:
    - zlib
    - libprotobuf {{ protobuf }}

test:
  files:
    - tests/include/*
  commands:
    - grpc_cpp_plugin < /dev/null

    - test -f $PREFIX/lib/libgrpc.so
    - test -f $PREFIX/lib/libgrpc_unsecure.so
    - test -f $PREFIX/lib/libgrpc++.so
    - test -f $PREFIX/lib/libgrpc++_unsecure.so

about:
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
  description: |
    gRPC is a modern, open source, high-performance remote procedure call
    (RPC) framework that can run anywhere. gRPC enables client and server
    applications to communicate transparently, and simplifies the building
    of connected systems.

    This package contains the gRPC C++ libraries and header files, as well
    as the code generation plugins.
  doc_url: https://grpc.io/docs/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
