{% set name = "grpc-cpp" %}
{% set version = "1.59.3" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: https://github.com/grpc/grpc
  git_rev: v{{version}}

build:
  number: 1
  string: h{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage('grpc-cpp', max_pin='x.x') }}
  ignore_run_exports:
    - libabseil
    - openssl
    - re2
    - c-ares

requirements:
  build:
    - {{ compiler('c') }}             #[ppc_arch != "p10"]
    - {{ compiler('cxx') }}           #[ppc_arch != "p10"]
    - cmake
    # `protoc` is also used for building
    - libprotobuf {{ libprotobuf }}
    - ninja
    # We need all host deps also in build for cross-compiling
    - libabseil {{ abseil_cpp }}     # [build_platform != target_platform]
    - c-ares      # [build_platform != target_platform]
    - re2         # [build_platform != target_platform]
    - openssl     # [build_platform != target_platform]
    - zlib {{ zlib }}        # [build_platform != target_platform]
  host:
    - libabseil  {{ abseil_cpp }}
    - c-ares
    - libprotobuf {{ libprotobuf }}
    - re2
    - zlib {{ zlib }}
    - openssl
  run:
    - zlib {{ zlib }}
    - libprotobuf {{ libprotobuf }}

test:
  files:
    - tests/include/*
  commands:
    - grpc_cpp_plugin < /dev/null

    - test -f $PREFIX/lib/libgrpc.so
    - test -f $PREFIX/lib/libgrpc_unsecure.so
    - test -f $PREFIX/lib/libgrpc++.so
    - test -f $PREFIX/lib/libgrpc++_unsecure.so

about:
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
  description: |
    gRPC is a modern, open source, high-performance remote procedure call
    (RPC) framework that can run anywhere. gRPC enables client and server
    applications to communicate transparently, and simplifies the building
    of connected systems.

    This package contains the gRPC C++ libraries and header files, as well
    as the code generation plugins.
  doc_url: https://grpc.io/docs/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
